export type AreaId = "seongsu" | "hongdae" | "gangnam";

export type PlaceCategory = "전시" | "카페" | "팝업" | "산책";

export type MobilePlace = {
  id: string;
  name: string;
  category: PlaceCategory;
  areaId: AreaId;
  area: string;
  address: string;
  description: string;
  distance: string;
  duration: string;
  price: string;
  tags: string[];
  hours: string;
  savedBy: number;
  lat: number;
  lng: number;
};

export type TripVisibility = "public" | "link" | "private";

export type FeedTrip = {
  id: string;
  title: string;
  description: string;
  authorHandle: string;
  authorName: string;
  areaId: AreaId;
  visibility: TripVisibility;
  placeIds: string[];
  likes: number;
  comments: number;
  saved: number;
  rankScore: number;
  isMine: boolean;
  publishedAt: string;
};

export const areaMeta: Record<AreaId, { name: string; coverage: string; center: { lat: number; lng: number } }> = {
  seongsu: { name: "성수", coverage: "건대 · 서울숲 · 뚝섬 일대", center: { lat: 37.5445, lng: 127.0507 } },
  hongdae: {
    name: "홍대",
    coverage: "합정 · 망원 · 연남 · 연희 · 상수 일대",
    center: { lat: 37.5564, lng: 126.9196 },
  },
  gangnam: { name: "강남", coverage: "강남역 · 신논현 · 역삼 · 논현 일대", center: { lat: 37.507, lng: 127.027 } },
};

export const promptExamples = [
  "성수에서 팝업 보고 카페 가는 데이트",
  "홍대에서 친구랑 걷고 먹는 코스",
  "강남에서 쇼핑하고 분위기 좋은 저녁",
  "비 오는 날 실내 위주로 성수 둘러보기",
  "혼자 조용히 걷고 커피 마시는 코스",
];

export function inferArea(prompt: string): AreaId {
  return detectAreaFromText(prompt) ?? "seongsu";
}

// Returns null (instead of defaulting to seongsu) when the text names no area,
// so callers can tell "explicitly mentioned" apart from "ambiguous, guess needed".
export function detectAreaFromText(prompt: string): AreaId | null {
  const text = prompt.replace(/\s/g, "");

  if (/홍대|합정|망원|연남|연희|상수/.test(text)) {
    return "hongdae";
  }

  if (/강남|신논현|역삼|논현|가로수길|신사/.test(text)) {
    return "gangnam";
  }

  if (/성수|건대|서울숲|뚝섬|자양/.test(text)) {
    return "seongsu";
  }

  return null;
}

export const placesByArea: Record<AreaId, MobilePlace[]> = {
  seongsu: [
    {
      id: "seongsu-forest-brunch",
      name: "폴앤폴리나 서울숲점",
      category: "카페",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 서울숲길",
      description: "숲 뷰를 보며 가볍게 시작하기 좋은 브런치 카페.",
      distance: "0.4km",
      duration: "60분",
      price: "1.5만원대",
      tags: ["브런치", "숲뷰", "데이트", "고급스러운"],
      hours: "09:00 - 21:00",
      savedBy: 812,
      lat: 37.5449,
      lng: 127.041,
    },
    {
      id: "seongsu-popup",
      name: "무신사 스탠다드 팝업",
      category: "팝업",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 성수이로",
      description: "이번 시즌 한정으로 열리는 트렌디한 브랜드 팝업.",
      distance: "0.9km",
      duration: "45분",
      price: "무료 입장",
      tags: ["한정", "포토존", "실내", "친구모임"],
      hours: "11:00 - 20:00",
      savedBy: 1204,
      lat: 37.5443,
      lng: 127.0557,
    },
    {
      id: "seongsu-roastery",
      name: "프릳츠커피 뚝섬점",
      category: "카페",
      areaId: "seongsu",
      area: "뚝섬",
      address: "서울 성동구 뚝섬로",
      description: "직접 로스팅한 원두로 내리는 커피와 조용한 좌석.",
      distance: "1.2km",
      duration: "50분",
      price: "8천원대",
      tags: ["로스터리", "휴식", "실내", "조용함"],
      hours: "10:00 - 22:00",
      savedBy: 566,
      lat: 37.5472,
      lng: 127.0479,
    },
    {
      id: "seongsu-gallery",
      name: "갤러리 팩토리 건대",
      category: "전시",
      areaId: "seongsu",
      area: "건대",
      address: "서울 광진구 능동로",
      description: "젊은 작가들의 작품을 소개하는 소규모 전시 공간.",
      distance: "2.1km",
      duration: "40분",
      price: "1만원",
      tags: ["전시", "문화", "실내", "조용함"],
      hours: "11:00 - 19:00",
      savedBy: 341,
      lat: 37.5407,
      lng: 127.0694,
    },
    {
      id: "seongsu-riverwalk",
      name: "서울숲 노을 산책길",
      category: "산책",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 뚝섬로 273",
      description: "해질녘 걷기 좋은 서울숲 메인 산책 코스.",
      distance: "0.6km",
      duration: "30분",
      price: "무료",
      tags: ["산책", "노을", "실외", "데이트"],
      hours: "24시간",
      savedBy: 998,
      lat: 37.5445,
      lng: 127.0397,
    },
    {
      id: "ss-forest-picnic-cafe",
      name: "카페 온더그라스",
      category: "카페",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 서울숲2길",
      description: "잔디밭을 보며 야외 좌석에서 즐기는 피크닉 감성 카페.",
      distance: "0.5km",
      duration: "45분",
      price: "9천원대",
      tags: ["피크닉", "야외석", "실외", "가족동반"],
      hours: "10:00 - 20:00",
      savedBy: 654,
      lat: 37.5453,
      lng: 127.0402,
    },
    {
      id: "ss-forest-jazz-bar",
      name: "블루노트 서울숲",
      category: "카페",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 서울숲4길",
      description: "재즈 선율이 흐르는 저녁 시간대 바 겸 카페.",
      distance: "1.3km",
      duration: "70분",
      price: "2만원대",
      tags: ["재즈", "저녁", "실내", "데이트"],
      hours: "18:00 - 01:00",
      savedBy: 512,
      lat: 37.5438,
      lng: 127.0432,
    },
    {
      id: "ss-forest-gallery-window",
      name: "디뮤지엄 윈도우",
      category: "전시",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 서울숲길 12",
      description: "지나가며 가볍게 감상하는 쇼윈도 기반 미니 전시.",
      distance: "0.7km",
      duration: "20분",
      price: "무료",
      tags: ["쇼윈도", "짧은관람", "실내", "혼자"],
      hours: "상시 이용",
      savedBy: 388,
      lat: 37.5461,
      lng: 127.0418,
    },
    {
      id: "ss-forest-picnic-walk",
      name: "서울숲 피크닉 트레일",
      category: "산책",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 서울숲길 27",
      description: "너른 잔디 피크닉존을 가로지르는 여유로운 산책로.",
      distance: "0.8km",
      duration: "35분",
      price: "무료",
      tags: ["잔디밭", "여유", "실외", "가족동반"],
      hours: "24시간",
      savedBy: 1122,
      lat: 37.5468,
      lng: 127.0405,
    },
    {
      id: "ss-forest-flower-popup",
      name: "이니스프리 플라워 팝업",
      category: "팝업",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 서울숲길 39",
      description: "계절 꽃으로 만드는 원데이 플라워 클래스 팝업.",
      distance: "0.9km",
      duration: "40분",
      price: "3만원대",
      tags: ["플라워", "클래스", "실내", "친구모임"],
      hours: "11:00 - 19:00",
      savedBy: 467,
      lat: 37.5442,
      lng: 127.0387,
    },
    {
      id: "ss-yeonmujang-print-gallery",
      name: "그라운드시소 성수",
      category: "전시",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 연무장7길 8",
      description: "그래픽 포스터와 독립 출판물을 함께 보는 전시 겸 숍.",
      distance: "0.5km",
      duration: "35분",
      price: "무료",
      tags: ["그래픽", "굿즈", "실내", "혼자"],
      hours: "12:00 - 19:00",
      savedBy: 812,
      lat: 37.5441,
      lng: 127.0571,
    },
    {
      id: "ss-yeonmujang-media-hall",
      name: "아르떼뮤지엄 성수",
      category: "전시",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 연무장길 31",
      description: "성수동 골목 안쪽의 몰입형 미디어 전시 공간.",
      distance: "0.4km",
      duration: "50분",
      price: "1만2천원",
      tags: ["미디어", "몰입형", "실내", "데이트"],
      hours: "11:00 - 20:00",
      savedBy: 1462,
      lat: 37.5457,
      lng: 127.0559,
    },
    {
      id: "ss-yeonmujang-archive-lab",
      name: "아모레퍼시픽 아카이브랩",
      category: "전시",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 성수이로 78",
      description: "로컬 브랜드의 기록과 프로토타입을 소개하는 아카이브 전시.",
      distance: "0.6km",
      duration: "45분",
      price: "무료",
      tags: ["아카이브", "브랜드", "실내", "조용함"],
      hours: "10:30 - 19:30",
      savedBy: 1034,
      lat: 37.5468,
      lng: 127.0528,
    },
    {
      id: "ss-yeonmujang-sneaker-popup",
      name: "나이키 라이즈 성수",
      category: "팝업",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 연무장길 45",
      description: "한정 컬러와 커스텀 체험존이 있는 스니커즈 팝업.",
      distance: "0.5km",
      duration: "35분",
      price: "무료",
      tags: ["스니커즈", "체험", "실내", "친구모임"],
      hours: "12:00 - 21:00",
      savedBy: 2521,
      lat: 37.5452,
      lng: 127.0581,
    },
    {
      id: "ss-yeonmujang-beauty-popup",
      name: "탬버린즈 뷰티 팝업",
      category: "팝업",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 성수이로 82",
      description: "샘플링과 퍼스널 컬러 체험이 있는 뷰티 브랜드 팝업.",
      distance: "0.6km",
      duration: "40분",
      price: "무료",
      tags: ["뷰티", "체험", "실내", "친구모임"],
      hours: "11:00 - 20:30",
      savedBy: 2214,
      lat: 37.5465,
      lng: 127.0539,
    },
    {
      id: "ss-yeonmujang-dessert-popup",
      name: "노티드 성수 팝업",
      category: "팝업",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 연무장3길 14",
      description: "주말 한정 메뉴가 나오는 디저트 브랜드 팝업.",
      distance: "0.5km",
      duration: "30분",
      price: "1만원대",
      tags: ["디저트", "한정", "실내", "포토존"],
      hours: "12:00 - 19:00",
      savedBy: 1805,
      lat: 37.5434,
      lng: 127.0566,
    },
    {
      id: "ss-yeonmujang-fragrance-popup",
      name: "탬버린즈 프래그런스",
      category: "팝업",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 연무장길 57",
      description: "시향 동선과 포토 부스가 있는 향수 브랜드 팝업.",
      distance: "0.7km",
      duration: "45분",
      price: "무료",
      tags: ["향수", "포토", "실내", "데이트"],
      hours: "11:30 - 21:00",
      savedBy: 1992,
      lat: 37.5425,
      lng: 127.0589,
    },
    {
      id: "ss-yeonmujang-object-shop",
      name: "오브젝트 성수",
      category: "팝업",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 연무장13길 11",
      description: "라이프스타일 브랜드가 시즌별로 바뀌는 오브젝트 팝업 숍.",
      distance: "0.8km",
      duration: "35분",
      price: "무료",
      tags: ["오브젝트", "라이프스타일", "실내", "혼자"],
      hours: "11:00 - 20:00",
      savedBy: 1588,
      lat: 37.5459,
      lng: 127.0604,
    },
    {
      id: "ss-yeonmujang-roastery",
      name: "센터커피 성수",
      category: "카페",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 연무장5길 9",
      description: "원두 선택지가 넓고 바 좌석이 좋은 로스터리 카페.",
      distance: "0.5km",
      duration: "40분",
      price: "6천원대",
      tags: ["로스터리", "바좌석", "실내", "혼자"],
      hours: "09:00 - 21:00",
      savedBy: 1750,
      lat: 37.5462,
      lng: 127.0568,
    },
    {
      id: "ss-yeonmujang-dessert-bar",
      name: "노티드 성수",
      category: "카페",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 성수이로14길 12",
      description: "작은 케이크와 시즌 디저트가 강점인 카페.",
      distance: "0.4km",
      duration: "45분",
      price: "9천원대",
      tags: ["디저트", "케이크", "실내", "친구모임"],
      hours: "11:00 - 22:00",
      savedBy: 1322,
      lat: 37.5438,
      lng: 127.0552,
    },
    {
      id: "ss-yeonmujang-yard-cafe",
      name: "대림창고 카페",
      category: "카페",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 연무장길 62",
      description: "마당 좌석이 있어 날씨 좋은 날 쉬기 좋은 카페.",
      distance: "0.7km",
      duration: "50분",
      price: "7천원대",
      tags: ["마당", "휴식", "실외", "친구모임"],
      hours: "10:00 - 21:30",
      savedBy: 1198,
      lat: 37.5429,
      lng: 127.0601,
    },
    {
      id: "ss-yeonmujang-night-gallery",
      name: "성수 아트홀",
      category: "전시",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 성수일로 89",
      description: "저녁 시간대 조명 연출이 좋은 야간 관람형 전시.",
      distance: "0.8km",
      duration: "45분",
      price: "1만5천원",
      tags: ["야간", "조명", "실내", "데이트"],
      hours: "14:00 - 22:00",
      savedBy: 1356,
      lat: 37.5417,
      lng: 127.0608,
    },
    {
      id: "ss-yeonmujang-street-walk",
      name: "성수 연무장길",
      category: "산책",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 연무장길 일대",
      description: "팝업과 카페를 촘촘히 연결하는 성수 핵심 골목 산책 루트.",
      distance: "0km",
      duration: "35분",
      price: "무료",
      tags: ["골목", "핵심루트", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 2011,
      lat: 37.5447,
      lng: 127.0563,
    },
    {
      id: "ss-industrial-walk",
      name: "성수 뚝섬로 공장길",
      category: "산책",
      areaId: "seongsu",
      area: "성수",
      address: "서울 성동구 성수이로 일대",
      description: "낡은 공장과 새 브랜드 공간이 섞인 성수 특유의 골목 산책.",
      distance: "0.6km",
      duration: "40분",
      price: "무료",
      tags: ["공장", "브랜드", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 1544,
      lat: 37.5419,
      lng: 127.0569,
    },
    {
      id: "ss-ttukseom-bakery",
      name: "브레드05",
      category: "카페",
      areaId: "seongsu",
      area: "뚝섬",
      address: "서울 성동구 왕십리로 90",
      description: "빵 종류가 많아 오전 코스의 첫 지점으로 좋은 베이커리 카페.",
      distance: "0.8km",
      duration: "35분",
      price: "7천원대",
      tags: ["베이커리", "오전", "실내", "가족동반"],
      hours: "08:30 - 21:00",
      savedBy: 886,
      lat: 37.5476,
      lng: 127.0491,
    },
    {
      id: "ss-ttukseom-art-window",
      name: "취향관 뚝섬",
      category: "전시",
      areaId: "seongsu",
      area: "뚝섬",
      address: "서울 성동구 아차산로 6",
      description: "퇴근 후 가볍게 들르기 좋은 쇼윈도형 미니 전시 공간.",
      distance: "0.9km",
      duration: "25분",
      price: "무료",
      tags: ["짧은관람", "야간", "실내", "혼자"],
      hours: "13:00 - 21:00",
      savedBy: 678,
      lat: 37.5474,
      lng: 127.0473,
    },
    {
      id: "ss-ttukseom-pet-popup",
      name: "몰리스펫샵 팝업",
      category: "팝업",
      areaId: "seongsu",
      area: "뚝섬",
      address: "서울 성동구 서울숲길 48",
      description: "반려동물 용품과 간식을 소개하는 서울숲 인근 팝업.",
      distance: "1.2km",
      duration: "35분",
      price: "무료",
      tags: ["펫", "간식", "실내", "반려동반"],
      hours: "11:00 - 18:00",
      savedBy: 764,
      lat: 37.5458,
      lng: 127.0427,
    },
    {
      id: "ss-ttukseom-station-walk",
      name: "뚝섬로 연결길",
      category: "산책",
      areaId: "seongsu",
      area: "뚝섬",
      address: "서울 성동구 왕십리로 일대",
      description: "성수와 서울숲 사이를 잇는 짧고 실용적인 도보 연결 코스.",
      distance: "0.9km",
      duration: "25분",
      price: "무료",
      tags: ["연결", "실용", "실외", "한적함"],
      hours: "상시 이용",
      savedBy: 830,
      lat: 37.5472,
      lng: 127.0479,
    },
    {
      id: "ss-forest-design-gallery",
      name: "일룸 디자인 갤러리",
      category: "전시",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 서울숲4길 21",
      description: "가구와 오브제를 중심으로 한 디자인 전시가 열리는 조용한 갤러리.",
      distance: "1.4km",
      duration: "40분",
      price: "무료",
      tags: ["디자인", "오브제", "실내", "조용함"],
      hours: "11:00 - 18:30",
      savedBy: 921,
      lat: 37.5444,
      lng: 127.0397,
    },
    {
      id: "ss-forest-teahouse",
      name: "오설록 티하우스",
      category: "카페",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 서울숲2길 32",
      description: "차와 가벼운 다과를 파는 조용한 공간, 산책 코스와 잘 붙음.",
      distance: "1.2km",
      duration: "45분",
      price: "8천원대",
      tags: ["차", "조용", "실내", "혼자"],
      hours: "10:30 - 20:00",
      savedBy: 1049,
      lat: 37.5449,
      lng: 127.0412,
    },
    {
      id: "ss-forest-north-walk",
      name: "서울숲 북측 그린로드",
      category: "산책",
      areaId: "seongsu",
      area: "서울숲",
      address: "서울 성동구 서울숲길 24",
      description: "서울숲 카페권과 자연스럽게 이어지는 가벼운 녹지 산책 루트.",
      distance: "1.5km",
      duration: "45분",
      price: "무료",
      tags: ["녹지", "연결", "실외", "한적함"],
      hours: "상시 이용",
      savedBy: 1876,
      lat: 37.5456,
      lng: 127.0387,
    },
    {
      id: "ss-konkuk-project-space",
      name: "커먼그라운드 프로젝트룸",
      category: "전시",
      areaId: "seongsu",
      area: "건대",
      address: "서울 광진구 아차산로 272",
      description: "건대입구 근처에서 짧게 보기 좋은 팝 아트 중심 프로젝트 전시.",
      distance: "1.5km",
      duration: "35분",
      price: "8천원",
      tags: ["팝아트", "건대", "실내", "친구모임"],
      hours: "11:30 - 20:30",
      savedBy: 1137,
      lat: 37.5426,
      lng: 127.0701,
    },
    {
      id: "ss-konkuk-latte-house",
      name: "카페 마마스 건대",
      category: "카페",
      areaId: "seongsu",
      area: "건대",
      address: "서울 광진구 동일로22길 42",
      description: "라떼와 쿠키가 유명한 건대 골목 카페.",
      distance: "1.4km",
      duration: "40분",
      price: "6천원대",
      tags: ["라떼", "쿠키", "실내", "데이트"],
      hours: "10:00 - 23:00",
      savedBy: 1477,
      lat: 37.5409,
      lng: 127.0694,
    },
    {
      id: "ss-konkuk-fashion-popup",
      name: "커버낫 팝업스토어",
      category: "팝업",
      areaId: "seongsu",
      area: "건대",
      address: "서울 광진구 아차산로30길 8",
      description: "스트리트 브랜드 신상품과 한정 굿즈를 볼 수 있는 패션 팝업.",
      distance: "1.3km",
      duration: "35분",
      price: "무료",
      tags: ["스트리트", "굿즈", "실내", "친구모임"],
      hours: "12:00 - 22:00",
      savedBy: 1698,
      lat: 37.5418,
      lng: 127.0682,
    },
    {
      id: "ss-konkuk-character-popup",
      name: "라인프렌즈 스토어",
      category: "팝업",
      areaId: "seongsu",
      area: "건대",
      address: "서울 광진구 동일로20길 96",
      description: "캐릭터 포토존과 랜덤 굿즈가 있는 팝업, 친구 코스에 좋음.",
      distance: "1.7km",
      duration: "45분",
      price: "무료",
      tags: ["캐릭터", "포토존", "실내", "친구모임"],
      hours: "11:00 - 21:30",
      savedBy: 2342,
      lat: 37.5401,
      lng: 127.0718,
    },
    {
      id: "ss-konkuk-food-walk",
      name: "건대 로데오거리",
      category: "산책",
      areaId: "seongsu",
      area: "건대",
      address: "서울 광진구 동일로22길 일대",
      description: "카페와 팝업 사이 식사 후보를 탐색하기 좋은 번화가 산책.",
      distance: "1.6km",
      duration: "35분",
      price: "무료",
      tags: ["번화가", "식사", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 1655,
      lat: 37.5407,
      lng: 127.0709,
    },
    {
      id: "ss-children-park-gallery",
      name: "어린이대공원 미술관",
      category: "전시",
      areaId: "seongsu",
      area: "광진",
      address: "서울 광진구 능동로 216",
      description: "공원 산책 전후로 들르기 좋은 밝은 분위기의 공공 전시 공간.",
      distance: "2.4km",
      duration: "30분",
      price: "무료",
      tags: ["공공", "공원", "실내", "가족동반"],
      hours: "10:00 - 17:30",
      savedBy: 722,
      lat: 37.5487,
      lng: 127.0803,
    },
    {
      id: "ss-children-park-market",
      name: "능동 마켓데이",
      category: "팝업",
      areaId: "seongsu",
      area: "광진",
      address: "서울 광진구 능동로 238",
      description: "주말마다 바뀌는 핸드메이드 셀러 중심의 작은 마켓.",
      distance: "2.5km",
      duration: "50분",
      price: "무료",
      tags: ["마켓", "핸드메이드", "실외", "가족동반"],
      hours: "13:00 - 18:00",
      savedBy: 888,
      lat: 37.5501,
      lng: 127.0792,
    },
    {
      id: "ss-children-park-loop",
      name: "어린이대공원 둘레길",
      category: "산책",
      areaId: "seongsu",
      area: "광진",
      address: "서울 광진구 능동로 216",
      description: "전시와 공원 휴식을 함께 묶기 좋은 넓은 산책 루프.",
      distance: "2.7km",
      duration: "70분",
      price: "무료",
      tags: ["공원", "루프", "실외", "가족동반"],
      hours: "05:00 - 22:00",
      savedBy: 1240,
      lat: 37.5508,
      lng: 127.0816,
    },
    {
      id: "ss-guui-photo-room",
      name: "구의 포토스튜디오",
      category: "전시",
      areaId: "seongsu",
      area: "구의",
      address: "서울 광진구 자양로 116",
      description: "동네 풍경과 여행 사진을 중심으로 큐레이션하는 사진 전시실.",
      distance: "3.0km",
      duration: "25분",
      price: "무료",
      tags: ["사진", "동네", "실내", "혼자"],
      hours: "13:00 - 19:00",
      savedBy: 433,
      lat: 37.5387,
      lng: 127.0859,
    },
    {
      id: "ss-guui-slow-cafe",
      name: "카페 낮잠 구의",
      category: "카페",
      areaId: "seongsu",
      area: "구의",
      address: "서울 광진구 자양로18길 17",
      description: "좌석 간격이 넓고 분위기가 차분해 대화 중심 코스에 잘 맞음.",
      distance: "2.8km",
      duration: "50분",
      price: "6천원대",
      tags: ["대화", "차분", "실내", "혼자"],
      hours: "09:00 - 21:00",
      savedBy: 742,
      lat: 37.5382,
      lng: 127.0831,
    },
    {
      id: "ss-guui-book-popup",
      name: "유어마인드 팝업",
      category: "팝업",
      areaId: "seongsu",
      area: "구의",
      address: "서울 광진구 자양로 130",
      description: "독립출판 신간과 작가 토크가 열리는 북 팝업.",
      distance: "2.9km",
      duration: "40분",
      price: "무료",
      tags: ["책", "토크", "실내", "혼자"],
      hours: "12:00 - 20:00",
      savedBy: 566,
      lat: 37.5377,
      lng: 127.0845,
    },
    {
      id: "ss-guui-market-walk",
      name: "구의시장길",
      category: "산책",
      areaId: "seongsu",
      area: "구의",
      address: "서울 광진구 구의동 일대",
      description: "동네 시장 분위기와 간식을 함께 탐색하는 로컬 산책 코스.",
      distance: "3.1km",
      duration: "40분",
      price: "무료",
      tags: ["시장", "로컬", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 705,
      lat: 37.5385,
      lng: 127.0868,
    },
    {
      id: "ss-jayang-river-cafe",
      name: "카페 한강뷰 자양",
      category: "카페",
      areaId: "seongsu",
      area: "자양",
      address: "서울 광진구 능동로 10",
      description: "강변 산책 뒤 들르기 좋은 창가 좌석 중심 카페.",
      distance: "2.1km",
      duration: "45분",
      price: "7천원대",
      tags: ["강변", "창가", "실내", "데이트"],
      hours: "10:00 - 22:30",
      savedBy: 930,
      lat: 37.5326,
      lng: 127.0678,
    },
    {
      id: "ss-jayang-food-popup",
      name: "배달의민족 푸드트럭",
      category: "팝업",
      areaId: "seongsu",
      area: "자양",
      address: "서울 광진구 뚝섬로 552",
      description: "한강 산책 전후로 들르기 좋은 간식 중심 푸드 팝업.",
      distance: "2.2km",
      duration: "30분",
      price: "1만원대",
      tags: ["푸드", "한강", "실외", "친구모임"],
      hours: "13:00 - 21:00",
      savedBy: 917,
      lat: 37.5344,
      lng: 127.0732,
    },
    {
      id: "ss-jayang-river-walk",
      name: "자양 한강공원길",
      category: "산책",
      areaId: "seongsu",
      area: "자양",
      address: "서울 광진구 자양동 한강공원",
      description: "해 질 무렵 체인의 마지막 지점으로 좋은 한강변 산책 루트.",
      distance: "2.4km",
      duration: "60분",
      price: "무료",
      tags: ["한강", "노을", "실외", "데이트"],
      hours: "상시 이용",
      savedBy: 2140,
      lat: 37.5299,
      lng: 127.0697,
    },
    {
      id: "ss-gwangjang-object-hall",
      name: "광장 크래프트홀",
      category: "전시",
      areaId: "seongsu",
      area: "광진",
      address: "서울 광진구 광장로 56",
      description: "한강 동쪽 동선에 붙이기 좋은 공예와 오브제 중심 전시.",
      distance: "4.4km",
      duration: "40분",
      price: "1만원",
      tags: ["공예", "오브제", "실내", "조용함"],
      hours: "11:00 - 19:00",
      savedBy: 602,
      lat: 37.5479,
      lng: 127.1032,
    },
    {
      id: "ss-gwangjang-outdoor-popup",
      name: "노스페이스 익스피리언스",
      category: "팝업",
      areaId: "seongsu",
      area: "광진",
      address: "서울 광진구 아차산로78길 90",
      description: "강변 산책 동선에 붙는 아웃도어 브랜드 체험 팝업.",
      distance: "4.2km",
      duration: "45분",
      price: "무료",
      tags: ["아웃도어", "강변", "실외", "친구모임"],
      hours: "11:00 - 19:00",
      savedBy: 697,
      lat: 37.5461,
      lng: 127.1021,
    },
    {
      id: "ss-sageundong-coffee",
      name: "카페 텍스처온텍스처",
      category: "카페",
      areaId: "seongsu",
      area: "성동",
      address: "서울 성동구 사근동길 18",
      description: "한양대 인근의 조용한 작업형 카페, 긴 체인 중 쉬어가기 좋음.",
      distance: "2.3km",
      duration: "55분",
      price: "5천원대",
      tags: ["작업", "조용", "실내", "혼자"],
      hours: "09:30 - 22:00",
      savedBy: 611,
      lat: 37.5588,
      lng: 127.0452,
    },
    {
      id: "ss-hanyang-art-corner",
      name: "한양대 아트코너 갤러리",
      category: "전시",
      areaId: "seongsu",
      area: "성동",
      address: "서울 성동구 마조로 22",
      description: "학생 작가와 신진 작가의 실험적인 작업을 볼 수 있는 소규모 전시.",
      distance: "2.1km",
      duration: "30분",
      price: "무료",
      tags: ["신진작가", "실험", "실내", "혼자"],
      hours: "12:00 - 18:00",
      savedBy: 389,
      lat: 37.5573,
      lng: 127.0435,
    },
  ],
  hongdae: [
    {
      id: "hongdae-mangwon-lunch",
      name: "망원시장 국수집",
      category: "카페",
      areaId: "hongdae",
      area: "망원",
      address: "서울 마포구 망원로",
      description: "로컬 무드 가득한 시장에서 즐기는 캐주얼 한 끼.",
      distance: "0.3km",
      duration: "50분",
      price: "1만원대",
      tags: ["로컬", "시장", "실내", "캐주얼"],
      hours: "10:00 - 20:00",
      savedBy: 723,
      lat: 37.5563,
      lng: 126.9016,
    },
    {
      id: "hongdae-yeonnam-walk",
      name: "연남동 경의선숲길",
      category: "산책",
      areaId: "hongdae",
      area: "연남",
      address: "서울 마포구 연남동",
      description: "경의선숲길을 따라 이어지는 여유로운 걷기 코스.",
      distance: "1.0km",
      duration: "35분",
      price: "무료",
      tags: ["숲길", "느긋함", "실외", "데이트"],
      hours: "24시간",
      savedBy: 1150,
      lat: 37.5619,
      lng: 126.9256,
    },
    {
      id: "hongdae-sangsu-shop",
      name: "무신사 스탠다드 상수",
      category: "팝업",
      areaId: "hongdae",
      area: "상수",
      address: "서울 마포구 와우산로",
      description: "취향 좋은 소품과 의류를 큐레이션한 편집숍.",
      distance: "1.6km",
      duration: "40분",
      price: "무료 입장",
      tags: ["편집숍", "취향", "실내", "친구모임"],
      hours: "12:00 - 21:00",
      savedBy: 489,
      lat: 37.5478,
      lng: 126.9227,
    },
    {
      id: "hongdae-hapjeong-dining",
      name: "라운지엑스 합정",
      category: "카페",
      areaId: "hongdae",
      area: "합정",
      address: "서울 마포구 양화로",
      description: "저녁 마무리로 좋은 조용한 분위기의 다이닝 바.",
      distance: "1.9km",
      duration: "70분",
      price: "3만원대",
      tags: ["다이닝", "분위기", "실내", "데이트"],
      hours: "17:00 - 24:00",
      savedBy: 645,
      lat: 37.5495,
      lng: 126.9139,
    },
    {
      id: "hongdae-yeonhui-cafe",
      name: "카페 담소 연희",
      category: "카페",
      areaId: "hongdae",
      area: "연희",
      address: "서울 서대문구 연희로",
      description: "주택가 골목 안에 숨은 조용한 독립 카페.",
      distance: "2.3km",
      duration: "45분",
      price: "7천원대",
      tags: ["독립카페", "조용함", "실내", "혼자"],
      hours: "11:00 - 20:00",
      savedBy: 402,
      lat: 37.5665,
      lng: 126.9346,
    },
    {
      id: "hd-hapjeong-river-cafe",
      name: "폴바셋 합정 리버뷰점",
      category: "카페",
      areaId: "hongdae",
      area: "합정",
      address: "서울 마포구 토정로",
      description: "한강이 살짝 보이는 창가 좌석의 여유로운 카페.",
      distance: "1.7km",
      duration: "50분",
      price: "8천원대",
      tags: ["리버뷰", "창가", "실내", "데이트"],
      hours: "10:00 - 22:00",
      savedBy: 733,
      lat: 37.5488,
      lng: 126.9152,
    },
    {
      id: "hd-hapjeong-craft-popup",
      name: "자주 합정 팝업",
      category: "팝업",
      areaId: "hongdae",
      area: "합정",
      address: "서울 마포구 양화로6길",
      description: "독립 브랜드 소품과 문구를 모은 시즌 팝업 스토어.",
      distance: "1.8km",
      duration: "35분",
      price: "무료 입장",
      tags: ["소품", "문구", "실내", "친구모임"],
      hours: "12:00 - 20:00",
      savedBy: 601,
      lat: 37.5501,
      lng: 126.9128,
    },
    {
      id: "hd-hapjeong-river-gallery",
      name: "스페이스 원 합정",
      category: "전시",
      areaId: "hongdae",
      area: "합정",
      address: "서울 마포구 토정로5길",
      description: "한강 조망을 배경으로 한 사진·설치 전시 공간.",
      distance: "1.9km",
      duration: "40분",
      price: "8천원",
      tags: ["설치미술", "한강", "실내", "조용함"],
      hours: "11:00 - 19:00",
      savedBy: 455,
      lat: 37.5479,
      lng: 126.9107,
    },
    {
      id: "hd-hapjeong-station-walk",
      name: "합정 책방골목",
      category: "산책",
      areaId: "hongdae",
      area: "합정",
      address: "서울 마포구 합정동 일대",
      description: "카페와 서점이 섞인 합정역 뒷골목을 걷는 코스.",
      distance: "1.6km",
      duration: "30분",
      price: "무료",
      tags: ["골목", "서점", "실외", "한적함"],
      hours: "상시 이용",
      savedBy: 812,
      lat: 37.5495,
      lng: 126.9145,
    },
    {
      id: "hd-mangwon-dessert",
      name: "성심당 망원점",
      category: "카페",
      areaId: "hongdae",
      area: "망원",
      address: "서울 마포구 포은로",
      description: "시장 골목 안 줄 서는 로컬 디저트 가게.",
      distance: "0.4km",
      duration: "30분",
      price: "6천원대",
      tags: ["로컬", "디저트", "실내", "캐주얼"],
      hours: "11:00 - 21:00",
      savedBy: 1024,
      lat: 37.5558,
      lng: 126.9031,
    },
    {
      id: "hd-mangwon-brewery-popup",
      name: "카브루 브루어리 팝업",
      category: "팝업",
      areaId: "hongdae",
      area: "망원",
      address: "서울 마포구 망원로7길",
      description: "수제맥주 브루어리가 여는 테이스팅 팝업 이벤트.",
      distance: "0.6km",
      duration: "50분",
      price: "2만원대",
      tags: ["수제맥주", "테이스팅", "실내", "친구모임"],
      hours: "17:00 - 23:00",
      savedBy: 689,
      lat: 37.5571,
      lng: 126.9003,
    },
    {
      id: "hd-mangwon-photo-gallery",
      name: "망원 포토아카이브",
      category: "전시",
      areaId: "hongdae",
      area: "망원",
      address: "서울 마포구 월드컵로",
      description: "동네 기록 사진을 모은 작은 로컬 사진 전시관.",
      distance: "0.7km",
      duration: "25분",
      price: "무료",
      tags: ["사진", "기록", "실내", "혼자"],
      hours: "12:00 - 19:00",
      savedBy: 341,
      lat: 37.5549,
      lng: 126.9042,
    },
    {
      id: "hd-mangwon-hanriver-walk",
      name: "망원한강공원 노을길",
      category: "산책",
      areaId: "hongdae",
      area: "망원",
      address: "서울 마포구 마포나루길",
      description: "노을 명당으로 유명한 망원한강공원 산책 코스.",
      distance: "1.1km",
      duration: "45분",
      price: "무료",
      tags: ["한강공원", "노을", "실외", "데이트"],
      hours: "24시간",
      savedBy: 1893,
      lat: 37.5544,
      lng: 126.8977,
    },
    {
      id: "hd-yeonnam-brunch-house",
      name: "런던베이글뮤지엄 연남",
      category: "카페",
      areaId: "hongdae",
      area: "연남",
      address: "서울 마포구 성미산로",
      description: "숲길 뷰가 좋은 연남동 대표 브런치 하우스.",
      distance: "0.5km",
      duration: "55분",
      price: "1.8만원대",
      tags: ["브런치", "숲길뷰", "실내", "데이트"],
      hours: "09:00 - 21:00",
      savedBy: 1466,
      lat: 37.5628,
      lng: 126.9241,
    },
    {
      id: "hd-yeonnam-goods-popup",
      name: "오브젝트 연남 팝업",
      category: "팝업",
      areaId: "hongdae",
      area: "연남",
      address: "서울 마포구 동교로38길",
      description: "일러스트레이터 굿즈를 모아 파는 한정 팝업.",
      distance: "0.6km",
      duration: "30분",
      price: "무료 입장",
      tags: ["굿즈", "일러스트", "실내", "친구모임"],
      hours: "12:00 - 20:00",
      savedBy: 977,
      lat: 37.5609,
      lng: 126.9268,
    },
    {
      id: "hd-yeonnam-illustration-gallery",
      name: "갤러리 나우 연남",
      category: "전시",
      areaId: "hongdae",
      area: "연남",
      address: "서울 마포구 성미산로29길",
      description: "신진 일러스트레이터 작품을 소개하는 소규모 갤러리.",
      distance: "0.7km",
      duration: "30분",
      price: "5천원",
      tags: ["일러스트", "신진작가", "실내", "혼자"],
      hours: "12:00 - 19:00",
      savedBy: 512,
      lat: 37.5624,
      lng: 126.9249,
    },
    {
      id: "hd-gyeonguiseon-walk",
      name: "경의선책거리",
      category: "산책",
      areaId: "hongdae",
      area: "연남",
      address: "서울 마포구 연남동 경의선숲길",
      description: "연남동을 가로지르는 경의선숲길 대표 산책 구간.",
      distance: "0.3km",
      duration: "40분",
      price: "무료",
      tags: ["숲길", "대표코스", "실외", "활기참"],
      hours: "24시간",
      savedBy: 2287,
      lat: 37.5615,
      lng: 126.9231,
    },
    {
      id: "hd-yeonhui-bookcafe",
      name: "북티크 연희",
      category: "카페",
      areaId: "hongdae",
      area: "연희",
      address: "서울 서대문구 연희로11길",
      description: "책과 함께 오래 머물기 좋은 조용한 독립 북카페.",
      distance: "2.4km",
      duration: "60분",
      price: "8천원대",
      tags: ["북카페", "독서", "실내", "혼자"],
      hours: "11:00 - 21:00",
      savedBy: 588,
      lat: 37.5671,
      lng: 126.9328,
    },
    {
      id: "hd-yeonhui-ceramics-popup",
      name: "이도 도자기 팝업",
      category: "팝업",
      areaId: "hongdae",
      area: "연희",
      address: "서울 서대문구 연희맛로",
      description: "핸드메이드 도자기 작가들의 소규모 마켓 팝업.",
      distance: "2.5km",
      duration: "35분",
      price: "무료 입장",
      tags: ["도자기", "핸드메이드", "실내", "친구모임"],
      hours: "12:00 - 18:00",
      savedBy: 402,
      lat: 37.5658,
      lng: 126.9352,
    },
    {
      id: "hd-yeonhui-photo-gallery",
      name: "취향관 연희",
      category: "전시",
      areaId: "hongdae",
      area: "연희",
      address: "서울 서대문구 연희로",
      description: "주택가 골목 안 조용한 사진 중심 갤러리.",
      distance: "2.3km",
      duration: "30분",
      price: "무료",
      tags: ["사진", "골목", "실내", "조용함"],
      hours: "11:00 - 18:00",
      savedBy: 297,
      lat: 37.5661,
      lng: 126.9339,
    },
    {
      id: "hd-yeonhui-alley-walk",
      name: "연희동 산책로",
      category: "산책",
      areaId: "hongdae",
      area: "연희",
      address: "서울 서대문구 연희동 일대",
      description: "카페와 갤러리가 섞인 연희동 조용한 주택가 산책.",
      distance: "2.4km",
      duration: "35분",
      price: "무료",
      tags: ["주택가", "조용", "실외", "한적함"],
      hours: "상시 이용",
      savedBy: 634,
      lat: 37.5669,
      lng: 126.9358,
    },
    {
      id: "hd-sangsu-brunch-cafe",
      name: "카페 온더플레이트 상수",
      category: "카페",
      areaId: "hongdae",
      area: "상수",
      address: "서울 마포구 와우산로29길",
      description: "한강 산책 전 가볍게 들르기 좋은 브런치 카페.",
      distance: "1.5km",
      duration: "50분",
      price: "1.5만원대",
      tags: ["브런치", "한강전", "실내", "데이트"],
      hours: "09:00 - 20:00",
      savedBy: 891,
      lat: 37.5484,
      lng: 126.9214,
    },
    {
      id: "hd-sangsu-vintage-popup",
      name: "빈티지 마르쉐 상수",
      category: "팝업",
      areaId: "hongdae",
      area: "상수",
      address: "서울 마포구 잔다리로",
      description: "빈티지 의류와 소품을 큐레이션한 주말 팝업.",
      distance: "1.4km",
      duration: "40분",
      price: "무료 입장",
      tags: ["빈티지", "큐레이션", "실내", "친구모임"],
      hours: "13:00 - 20:00",
      savedBy: 703,
      lat: 37.5471,
      lng: 126.9241,
    },
    {
      id: "hd-sangsu-sound-gallery",
      name: "사운드 파운데이션",
      category: "전시",
      areaId: "hongdae",
      area: "상수",
      address: "서울 마포구 와우산로",
      description: "음악과 시각 설치를 결합한 실험적 사운드 전시.",
      distance: "1.6km",
      duration: "40분",
      price: "1만원",
      tags: ["사운드", "설치", "실내", "혼자"],
      hours: "13:00 - 21:00",
      savedBy: 448,
      lat: 37.5482,
      lng: 126.9219,
    },
    {
      id: "hd-sangsu-river-walk",
      name: "상수역 한강길",
      category: "산책",
      areaId: "hongdae",
      area: "상수",
      address: "서울 마포구 토정로 일대",
      description: "상수역에서 한강 방향으로 짧게 이어지는 산책로.",
      distance: "1.3km",
      duration: "30분",
      price: "무료",
      tags: ["강변", "짧은코스", "실외", "한적함"],
      hours: "24시간",
      savedBy: 967,
      lat: 37.5466,
      lng: 126.9192,
    },
    {
      id: "hd-hongdae-playground-popup",
      name: "홍대 인디마켓",
      category: "팝업",
      areaId: "hongdae",
      area: "홍대",
      address: "서울 마포구 어울마당로",
      description: "홍대 놀이터 앞에서 열리는 인디 브랜드 마켓 팝업.",
      distance: "0.4km",
      duration: "45분",
      price: "무료 입장",
      tags: ["인디", "마켓", "실외", "친구모임"],
      hours: "13:00 - 20:00",
      savedBy: 1204,
      lat: 37.5535,
      lng: 126.9224,
    },
    {
      id: "hd-hongdae-street-walk",
      name: "홍대 걷고싶은거리",
      category: "산책",
      areaId: "hongdae",
      area: "홍대",
      address: "서울 마포구 홍익로",
      description: "버스킹과 상점 구경을 함께 즐기는 홍대 대표 거리.",
      distance: "0.3km",
      duration: "35분",
      price: "무료",
      tags: ["버스킹", "대표거리", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 2013,
      lat: 37.5551,
      lng: 126.9236,
    },
    {
      id: "hd-hongdae-street-gallery",
      name: "그래피티 갤러리 홍대",
      category: "전시",
      areaId: "hongdae",
      area: "홍대",
      address: "서울 마포구 와우산로29나길",
      description: "그래피티와 스트리트 아트를 소개하는 실내 갤러리.",
      distance: "0.5km",
      duration: "35분",
      price: "8천원",
      tags: ["그래피티", "스트리트", "실내", "친구모임"],
      hours: "12:00 - 20:00",
      savedBy: 856,
      lat: 37.5543,
      lng: 126.9251,
    },
    {
      id: "hd-hongdae-rooftop-cafe",
      name: "카페 노티드 루프탑",
      category: "카페",
      areaId: "hongdae",
      area: "홍대",
      address: "서울 마포구 어울마당로5길",
      description: "홍대 전경을 내려다보는 루프탑 좌석 카페.",
      distance: "0.6km",
      duration: "50분",
      price: "9천원대",
      tags: ["루프탑", "전망", "실외", "데이트"],
      hours: "12:00 - 23:00",
      savedBy: 1382,
      lat: 37.5539,
      lng: 126.9218,
    },
    {
      id: "hd-hapjeong-bookcafe",
      name: "당인리책발전소",
      category: "카페",
      areaId: "hongdae",
      area: "합정",
      address: "서울 마포구 독막로",
      description: "출판사 거리 근처 책과 커피를 함께 즐기는 카페.",
      distance: "1.9km",
      duration: "45분",
      price: "7천원대",
      tags: ["출판사거리", "독서", "실내", "혼자"],
      hours: "10:00 - 21:00",
      savedBy: 677,
      lat: 37.5502,
      lng: 126.9161,
    },
    {
      id: "hd-hapjeong-artmarket-popup",
      name: "아트마켓 언리미티드",
      category: "팝업",
      areaId: "hongdae",
      area: "합정",
      address: "서울 마포구 양화로",
      description: "일러스트 작가들의 아트 상품을 파는 주말 마켓.",
      distance: "1.8km",
      duration: "40분",
      price: "무료 입장",
      tags: ["아트마켓", "일러스트", "실외", "친구모임"],
      hours: "12:00 - 19:00",
      savedBy: 559,
      lat: 37.5492,
      lng: 126.9134,
    },
    {
      id: "hd-mangwon-graphic-gallery",
      name: "타이포그라피 랩 망원",
      category: "전시",
      areaId: "hongdae",
      area: "망원",
      address: "서울 마포구 망원로",
      description: "포스터와 타이포그래피 중심의 작은 그래픽 갤러리.",
      distance: "0.5km",
      duration: "25분",
      price: "무료",
      tags: ["그래픽", "타이포", "실내", "혼자"],
      hours: "12:00 - 19:00",
      savedBy: 288,
      lat: 37.5567,
      lng: 126.9038,
    },
    {
      id: "hd-mangwon-garden-brunch",
      name: "가든 브런치 망원",
      category: "카페",
      areaId: "hongdae",
      area: "망원",
      address: "서울 마포구 망원로9길",
      description: "작은 정원 좌석이 있는 여유로운 브런치 카페.",
      distance: "0.6km",
      duration: "55분",
      price: "1.6만원대",
      tags: ["가든", "브런치", "실외", "데이트"],
      hours: "09:30 - 20:00",
      savedBy: 812,
      lat: 37.5576,
      lng: 126.9021,
    },
    {
      id: "hd-yeonnam-goods-popup-2",
      name: "자주 리빙 팝업",
      category: "팝업",
      areaId: "hongdae",
      area: "연남",
      address: "서울 마포구 동교로",
      description: "리빙 소품과 향초를 소개하는 계절 한정 팝업.",
      distance: "0.5km",
      duration: "30분",
      price: "무료 입장",
      tags: ["리빙", "향초", "실내", "친구모임"],
      hours: "12:00 - 20:00",
      savedBy: 468,
      lat: 37.5613,
      lng: 126.9273,
    },
    {
      id: "hd-yeonnam-photostudio-gallery",
      name: "레트로포토 연남",
      category: "전시",
      areaId: "hongdae",
      area: "연남",
      address: "서울 마포구 성미산로1길",
      description: "옛 사진관 공간을 개조한 레트로 사진 전시.",
      distance: "0.6km",
      duration: "30분",
      price: "6천원",
      tags: ["레트로", "사진관", "실내", "친구모임"],
      hours: "12:00 - 19:00",
      savedBy: 379,
      lat: 37.5631,
      lng: 126.9259,
    },
    {
      id: "hd-yeonhui-winebar",
      name: "비아트로 연희",
      category: "카페",
      areaId: "hongdae",
      area: "연희",
      address: "서울 서대문구 연희로32길",
      description: "저녁 코스 마무리로 좋은 조용한 와인바.",
      distance: "2.6km",
      duration: "75분",
      price: "3.5만원대",
      tags: ["와인", "저녁", "실내", "데이트"],
      hours: "18:00 - 01:00",
      savedBy: 521,
      lat: 37.5674,
      lng: 126.9312,
    },
    {
      id: "hd-yeonhui-market-popup",
      name: "연희 소셜마켓",
      category: "팝업",
      areaId: "hongdae",
      area: "연희",
      address: "서울 서대문구 연희맛로11길",
      description: "동네 셀러들이 모이는 소규모 주말 마켓 팝업.",
      distance: "2.5km",
      duration: "40분",
      price: "무료",
      tags: ["동네마켓", "주말", "실외", "가족동반"],
      hours: "13:00 - 18:00",
      savedBy: 356,
      lat: 37.5662,
      lng: 126.9367,
    },
    {
      id: "hd-sangsu-craft-gallery",
      name: "크래프트룸 상수",
      category: "전시",
      areaId: "hongdae",
      area: "상수",
      address: "서울 마포구 와우산로21길",
      description: "도예와 금속 공예를 함께 보는 실용 공예 갤러리.",
      distance: "1.5km",
      duration: "35분",
      price: "7천원",
      tags: ["도예", "공예", "실내", "혼자"],
      hours: "12:00 - 19:00",
      savedBy: 322,
      lat: 37.5475,
      lng: 126.9231,
    },
    {
      id: "hd-sangsu-brewing-cafe",
      name: "커피리브레 상수",
      category: "카페",
      areaId: "hongdae",
      area: "상수",
      address: "서울 마포구 와우산로17길",
      description: "핸드드립 브루잉을 전문으로 하는 조용한 카페.",
      distance: "1.4km",
      duration: "45분",
      price: "8천원대",
      tags: ["핸드드립", "전문", "실내", "혼자"],
      hours: "10:00 - 21:00",
      savedBy: 704,
      lat: 37.5480,
      lng: 126.9235,
    },
    {
      id: "hd-hongdae-mural-walk",
      name: "홍대 벽화마을길",
      category: "산책",
      areaId: "hongdae",
      area: "홍대",
      address: "서울 마포구 잔다리로6길",
      description: "알록달록한 벽화가 이어지는 사진 찍기 좋은 골목.",
      distance: "0.5km",
      duration: "25분",
      price: "무료",
      tags: ["벽화", "포토", "실외", "친구모임"],
      hours: "상시 이용",
      savedBy: 1508,
      lat: 37.5528,
      lng: 126.9209,
    },
    {
      id: "hd-hongdae-hiphop-popup",
      name: "스투시 힙합 팝업",
      category: "팝업",
      areaId: "hongdae",
      area: "홍대",
      address: "서울 마포구 와우산로27길",
      description: "스트릿 브랜드와 음악이 함께하는 힙합 컬처 팝업.",
      distance: "0.4km",
      duration: "40분",
      price: "무료 입장",
      tags: ["힙합", "컬처", "실내", "친구모임"],
      hours: "14:00 - 22:00",
      savedBy: 933,
      lat: 37.5546,
      lng: 126.9245,
    },
    {
      id: "hd-hapjeong-sunset-walk",
      name: "합정 한강노을길",
      category: "산책",
      areaId: "hongdae",
      area: "합정",
      address: "서울 마포구 합정동 한강변",
      description: "한강 노을을 보며 마무리하기 좋은 짧은 산책 코스.",
      distance: "2.0km",
      duration: "40분",
      price: "무료",
      tags: ["노을", "마무리", "실외", "데이트"],
      hours: "24시간",
      savedBy: 1276,
      lat: 37.5473,
      lng: 126.9098,
    },
    {
      id: "hd-mangwon-community-popup",
      name: "망원 로컬마켓",
      category: "팝업",
      areaId: "hongdae",
      area: "망원",
      address: "서울 마포구 포은로8길",
      description: "동네 소상공인이 모이는 커뮤니티 기반 마켓.",
      distance: "0.5km",
      duration: "45분",
      price: "무료",
      tags: ["커뮤니티", "소상공인", "실외", "가족동반"],
      hours: "12:00 - 19:00",
      savedBy: 498,
      lat: 37.5562,
      lng: 126.9009,
    },
    {
      id: "hd-yeonnam-teahouse",
      name: "오설록 티하우스 연남",
      category: "카페",
      areaId: "hongdae",
      area: "연남",
      address: "서울 마포구 성미산로2길",
      description: "차분하게 차 한 잔 즐기기 좋은 티 전문 카페.",
      distance: "0.6km",
      duration: "50분",
      price: "9천원대",
      tags: ["티", "차분", "실내", "혼자"],
      hours: "11:00 - 21:00",
      savedBy: 645,
      lat: 37.5621,
      lng: 126.9263,
    },
    {
      id: "hd-yeonhui-path-walk",
      name: "연희 카페골목길",
      category: "산책",
      areaId: "hongdae",
      area: "연희",
      address: "서울 서대문구 연희로 일대",
      description: "카페 거리와 이어지는 완만한 오르막 산책로.",
      distance: "2.7km",
      duration: "40분",
      price: "무료",
      tags: ["오르막", "카페거리", "실외", "한적함"],
      hours: "상시 이용",
      savedBy: 489,
      lat: 37.5678,
      lng: 126.9341,
    },
    {
      id: "hd-sangsu-gallery-cafe",
      name: "취향관 카페 상수",
      category: "카페",
      areaId: "hongdae",
      area: "상수",
      address: "서울 마포구 와우산로25길",
      description: "작은 전시 벽을 함께 운영하는 갤러리 겸 카페.",
      distance: "1.6km",
      duration: "45분",
      price: "8천원대",
      tags: ["갤러리", "전시벽", "실내", "혼자"],
      hours: "11:00 - 20:00",
      savedBy: 512,
      lat: 37.5477,
      lng: 126.9224,
    },
    {
      id: "hd-hongdae-arttoy-gallery",
      name: "아트토이 뮤지엄 홍대",
      category: "전시",
      areaId: "hongdae",
      area: "홍대",
      address: "서울 마포구 어울마당로9길",
      description: "디자이너 피규어와 아트토이를 소개하는 전시.",
      distance: "0.5km",
      duration: "35분",
      price: "9천원",
      tags: ["피규어", "아트토이", "실내", "친구모임"],
      hours: "12:00 - 20:00",
      savedBy: 1041,
      lat: 37.5533,
      lng: 126.9231,
    },
    {
      id: "hd-hapjeong-dessert-popup",
      name: "노티드 합정 팝업",
      category: "팝업",
      areaId: "hongdae",
      area: "합정",
      address: "서울 마포구 독막로9길",
      description: "시즌 한정 디저트를 선보이는 브랜드 팝업.",
      distance: "1.8km",
      duration: "30분",
      price: "1.2만원대",
      tags: ["디저트", "시즌한정", "실내", "친구모임"],
      hours: "12:00 - 20:00",
      savedBy: 823,
      lat: 37.5497,
      lng: 126.9149,
    },
    {
      id: "hd-mangwon-nightmarket-walk",
      name: "망원 야시장길",
      category: "산책",
      areaId: "hongdae",
      area: "망원",
      address: "서울 마포구 포은로 일대",
      description: "저녁 시간대 노점과 함께 걷는 망원시장 야간 산책.",
      distance: "0.4km",
      duration: "30분",
      price: "무료",
      tags: ["야시장", "노점", "실외", "활기참"],
      hours: "17:00 - 22:00",
      savedBy: 1147,
      lat: 37.5555,
      lng: 126.9027,
    },
    {
      id: "hd-yeonnam-fragrance-popup",
      name: "논픽션 프래그런스",
      category: "팝업",
      areaId: "hongdae",
      area: "연남",
      address: "서울 마포구 동교로36길",
      description: "니치 향수 브랜드의 시향 중심 체험 팝업.",
      distance: "0.7km",
      duration: "35분",
      price: "무료",
      tags: ["향수", "시향", "실내", "데이트"],
      hours: "12:00 - 20:00",
      savedBy: 587,
      lat: 37.5606,
      lng: 126.9282,
    },
  ],
  gangnam: [
    {
      id: "gangnam-sinsa-brunch",
      name: "카페 온더플레이트 신논현",
      category: "카페",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로",
      description: "프리미엄한 분위기로 하루를 시작하는 신논현 브런치 레스토랑.",
      distance: "0.5km",
      duration: "60분",
      price: "2.5만원대",
      tags: ["브런치", "프리미엄", "실내", "데이트"],
      hours: "09:00 - 21:00",
      savedBy: 877,
      lat: 37.5044,
      lng: 127.0246,
    },
    {
      id: "gangnam-garosugil-showroom",
      name: "젠틀몬스터 신논현 쇼룸",
      category: "팝업",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 봉은사로",
      description: "시즌 컬렉션을 미리 만나볼 수 있는 브랜드 쇼룸.",
      distance: "0.8km",
      duration: "45분",
      price: "무료 입장",
      tags: ["쇼핑", "쇼룸", "실내", "친구모임"],
      hours: "11:00 - 20:00",
      savedBy: 1032,
      lat: 37.5052,
      lng: 127.0231,
    },
    {
      id: "gangnam-apgujeong-dessert",
      name: "설빙 강남역점",
      category: "카페",
      areaId: "gangnam",
      area: "강남역",
      address: "서울 강남구 강남대로",
      description: "정갈한 디저트와 함께 잠시 쉬어가는 강남역 티타임.",
      distance: "1.4km",
      duration: "40분",
      price: "1.2만원대",
      tags: ["디저트", "휴식", "실내", "친구모임"],
      hours: "10:00 - 22:00",
      savedBy: 594,
      lat: 37.4986,
      lng: 127.0276,
    },
    {
      id: "gangnam-cheongdam-wine",
      name: "비아트로 논현",
      category: "카페",
      areaId: "gangnam",
      area: "논현",
      address: "서울 강남구 논현동",
      description: "분위기 있는 저녁 마무리를 위한 와인바.",
      distance: "2.0km",
      duration: "80분",
      price: "4만원대",
      tags: ["와인", "분위기", "실내", "데이트"],
      hours: "18:00 - 01:00",
      savedBy: 711,
      lat: 37.5112,
      lng: 127.0231,
    },
    {
      id: "gangnam-sinsa-gallery",
      name: "국제갤러리 신논현",
      category: "전시",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로 안쪽",
      description: "현대미술 작품을 감상할 수 있는 프라이빗 갤러리.",
      distance: "1.1km",
      duration: "35분",
      price: "무료",
      tags: ["전시", "갤러리", "실내", "고급스러운"],
      hours: "11:00 - 19:00",
      savedBy: 288,
      lat: 37.5038,
      lng: 127.0253,
    },
    {
      id: "gn-sinsa-roastery",
      name: "프릳츠커피 신논현",
      category: "카페",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 봉은사로4길",
      description: "원두 셀렉션이 다양한 프리미엄 로스터리 카페.",
      distance: "0.6km",
      duration: "45분",
      price: "9천원대",
      tags: ["로스터리", "프리미엄", "실내", "혼자"],
      hours: "09:00 - 22:00",
      savedBy: 902,
      lat: 37.5061,
      lng: 127.0238,
    },
    {
      id: "gn-sinsa-edit-popup",
      name: "무신사 신논현 팝업",
      category: "팝업",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로 뒷골목",
      description: "시즌마다 큐레이션이 바뀌는 편집숍 한정 팝업.",
      distance: "0.7km",
      duration: "40분",
      price: "무료 입장",
      tags: ["편집숍", "큐레이션", "실내", "친구모임"],
      hours: "11:00 - 21:00",
      savedBy: 764,
      lat: 37.5049,
      lng: 127.0219,
    },
    {
      id: "gn-sinsa-photo-gallery",
      name: "매거진 갤러리 신논현",
      category: "전시",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 봉은사로2길",
      description: "패션 화보와 아티스트 사진을 소개하는 전시 공간.",
      distance: "0.9km",
      duration: "35분",
      price: "1만원",
      tags: ["패션", "화보", "실내", "고급스러운"],
      hours: "11:00 - 19:00",
      savedBy: 519,
      lat: 37.5033,
      lng: 127.0261,
    },
    {
      id: "gn-dosan-park-walk",
      name: "신논현 뒷골목 산책로",
      category: "산책",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로 일대",
      description: "카페와 소품숍이 이어지는 조용한 신논현 산책 코스.",
      distance: "0.8km",
      duration: "35분",
      price: "무료",
      tags: ["골목", "조용함", "실외", "한적함"],
      hours: "24시간",
      savedBy: 1385,
      lat: 37.5057,
      lng: 127.0227,
    },
    {
      id: "gn-garosugil-brunch",
      name: "카페 마마스 가로수길",
      category: "카페",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 가로수길 안쪽",
      description: "은행나무 거리 뷰가 좋은 대표 브런치 레스토랑.",
      distance: "0.5km",
      duration: "60분",
      price: "2.2만원대",
      tags: ["브런치", "은행나무", "실내", "데이트"],
      hours: "09:00 - 21:00",
      savedBy: 1622,
      lat: 37.5202,
      lng: 127.0225,
    },
    {
      id: "gn-garosugil-flagship-popup",
      name: "아디다스 플래그십 가로수길",
      category: "팝업",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 가로수길",
      description: "글로벌 브랜드의 대형 플래그십 체험 팝업.",
      distance: "0.6km",
      duration: "50분",
      price: "무료 입장",
      tags: ["플래그십", "체험", "실내", "친구모임"],
      hours: "11:00 - 21:00",
      savedBy: 1987,
      lat: 37.5209,
      lng: 127.0229,
    },
    {
      id: "gn-garosugil-artwall",
      name: "가로수길 아트월",
      category: "전시",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 신사동 536",
      description: "대형 벽면 아트워크를 감상하는 오픈형 전시 공간.",
      distance: "0.4km",
      duration: "25분",
      price: "무료",
      tags: ["벽화", "오픈형", "실외", "친구모임"],
      hours: "상시 이용",
      savedBy: 738,
      lat: 37.5211,
      lng: 127.0221,
    },
    {
      id: "gn-garosugil-walk",
      name: "가로수길 메인스트리트",
      category: "산책",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 가로수길 일대",
      description: "쇼핑과 카페를 함께 즐기는 가로수길 대표 산책로.",
      distance: "0.3km",
      duration: "30분",
      price: "무료",
      tags: ["쇼핑", "대표거리", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 2205,
      lat: 37.5200,
      lng: 127.0233,
    },
    {
      id: "gn-apgujeong-rodeo-cafe",
      name: "카페 온리 강남대로",
      category: "카페",
      areaId: "gangnam",
      area: "강남역",
      address: "서울 강남구 강남대로94길",
      description: "강남역 대로변 한복판의 트렌디한 시그니처 카페.",
      distance: "1.5km",
      duration: "45분",
      price: "1.1만원대",
      tags: ["시그니처", "트렌디", "실내", "데이트"],
      hours: "10:00 - 22:00",
      savedBy: 1143,
      lat: 37.4995,
      lng: 127.0286,
    },
    {
      id: "gn-apgujeong-beauty-popup",
      name: "라네즈 뷰티 팝업 강남",
      category: "팝업",
      areaId: "gangnam",
      area: "강남역",
      address: "서울 강남구 강남대로102길",
      description: "퍼스널 컬러 진단이 있는 뷰티 브랜드 체험 팝업.",
      distance: "1.3km",
      duration: "40분",
      price: "무료",
      tags: ["퍼스널컬러", "체험", "실내", "친구모임"],
      hours: "11:00 - 20:00",
      savedBy: 1298,
      lat: 37.4972,
      lng: 127.0261,
    },
    {
      id: "gn-apgujeong-gallery",
      name: "교보아트스페이스 강남",
      category: "전시",
      areaId: "gangnam",
      area: "강남역",
      address: "서울 강남구 강남대로",
      description: "직장인들도 가볍게 들르는 강남역 기획 전시 공간.",
      distance: "1.4km",
      duration: "40분",
      price: "1만원",
      tags: ["기획전시", "오피스가", "실내", "혼자"],
      hours: "10:30 - 18:30",
      savedBy: 662,
      lat: 37.4998,
      lng: 127.0264,
    },
    {
      id: "gn-apgujeong-rodeo-walk",
      name: "강남대로 스트리트",
      category: "산책",
      areaId: "gangnam",
      area: "강남역",
      address: "서울 강남구 강남대로 일대",
      description: "쇼핑몰과 브랜드 매장이 늘어선 강남역 대표 산책.",
      distance: "1.2km",
      duration: "30분",
      price: "무료",
      tags: ["쇼핑", "번화가", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 1734,
      lat: 37.4979,
      lng: 127.0276,
    },
    {
      id: "gn-cheongdam-dessert",
      name: "패션5 논현",
      category: "카페",
      areaId: "gangnam",
      area: "논현",
      address: "서울 강남구 논현로",
      description: "플레이팅이 화려한 디저트로 유명한 프리미엄 카페.",
      distance: "2.1km",
      duration: "50분",
      price: "1.8만원대",
      tags: ["디저트", "플레이팅", "실내", "고급스러운"],
      hours: "11:00 - 21:00",
      savedBy: 1567,
      lat: 37.5128,
      lng: 127.0246,
    },
    {
      id: "gn-cheongdam-luxury-popup",
      name: "까사미아 리빙 팝업",
      category: "팝업",
      areaId: "gangnam",
      area: "논현",
      address: "서울 강남구 논현로 가구거리",
      description: "논현 가구거리에서 여는 리빙 브랜드 시즌 팝업.",
      distance: "2.0km",
      duration: "45분",
      price: "무료 입장",
      tags: ["리빙", "가구거리", "실내", "친구모임"],
      hours: "11:00 - 20:00",
      savedBy: 2098,
      lat: 37.5108,
      lng: 127.0218,
    },
    {
      id: "gn-cheongdam-art-gallery",
      name: "논현 아트스페이스",
      category: "전시",
      areaId: "gangnam",
      area: "논현",
      address: "서울 강남구 논현로12길",
      description: "동시대 작가들의 소규모 기획전이 열리는 갤러리.",
      distance: "1.9km",
      duration: "45분",
      price: "1.5만원",
      tags: ["기획전시", "동시대미술", "실내", "혼자"],
      hours: "10:00 - 19:00",
      savedBy: 981,
      lat: 37.5119,
      lng: 127.0225,
    },
    {
      id: "gn-cheongdam-street-walk",
      name: "논현 가구거리 산책",
      category: "산책",
      areaId: "gangnam",
      area: "논현",
      address: "서울 강남구 논현로 일대",
      description: "쇼룸과 가구거리가 늘어선 논현동 대표 산책 코스.",
      distance: "2.2km",
      duration: "35분",
      price: "무료",
      tags: ["가구거리", "쇼룸", "실외", "한적함"],
      hours: "상시 이용",
      savedBy: 1156,
      lat: 37.5108,
      lng: 127.0212,
    },
    {
      id: "gn-sinsa-brunch-garden",
      name: "가든파이브 신논현",
      category: "카페",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로 뒷길",
      description: "야외 정원 좌석이 있는 조용한 브런치 카페.",
      distance: "0.7km",
      duration: "55분",
      price: "2만원대",
      tags: ["정원", "브런치", "실외", "데이트"],
      hours: "09:30 - 20:30",
      savedBy: 934,
      lat: 37.5041,
      lng: 127.0215,
    },
    {
      id: "gn-sinsa-fragrance-popup",
      name: "탬버린즈 신논현 플래그십",
      category: "팝업",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 봉은사로6길",
      description: "니치 향수 브랜드의 프라이빗 시향 팝업.",
      distance: "0.8km",
      duration: "35분",
      price: "무료",
      tags: ["니치향수", "시향", "실내", "데이트"],
      hours: "12:00 - 20:00",
      savedBy: 823,
      lat: 37.5066,
      lng: 127.0249,
    },
    {
      id: "gn-dosan-gallery",
      name: "일룸 신논현 갤러리",
      category: "전시",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로8길",
      description: "건축과 공간 디자인을 다루는 전시 공간.",
      distance: "1.0km",
      duration: "35분",
      price: "8천원",
      tags: ["건축", "공간디자인", "실내", "혼자"],
      hours: "11:00 - 19:00",
      savedBy: 447,
      lat: 37.5029,
      lng: 127.0233,
    },
    {
      id: "gn-sinsa-alley-walk",
      name: "신논현 뒷골목길",
      category: "산책",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로 뒷골목 일대",
      description: "강남대로보다 한적한 신논현 뒷골목 산책.",
      distance: "0.6km",
      duration: "30분",
      price: "무료",
      tags: ["뒷골목", "한적함", "실외", "한적함"],
      hours: "상시 이용",
      savedBy: 1042,
      lat: 37.5047,
      lng: 127.0209,
    },
    {
      id: "gn-garosugil-dessertbar",
      name: "노티드 가로수길",
      category: "카페",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 가로수길4길",
      description: "커스텀 디저트를 바에서 즐기는 트렌디한 공간.",
      distance: "0.5km",
      duration: "40분",
      price: "1.4만원대",
      tags: ["디저트바", "커스텀", "실내", "친구모임"],
      hours: "12:00 - 22:00",
      savedBy: 1089,
      lat: 37.5197,
      lng: 127.0219,
    },
    {
      id: "gn-garosugil-jewelry-popup",
      name: "이니스프리 주얼리 팝업",
      category: "팝업",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 가로수길6길",
      description: "인디 주얼리 브랜드들의 소규모 컬렉션 팝업.",
      distance: "0.6km",
      duration: "30분",
      price: "무료 입장",
      tags: ["주얼리", "인디브랜드", "실내", "친구모임"],
      hours: "12:00 - 20:00",
      savedBy: 675,
      lat: 37.5204,
      lng: 127.0217,
    },
    {
      id: "gn-garosugil-photoexhibit",
      name: "매거진 B 사진전",
      category: "전시",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 가로수길8길",
      description: "패션 사진작가들의 그룹 사진전이 열리는 공간.",
      distance: "0.5km",
      duration: "30분",
      price: "무료",
      tags: ["패션사진", "그룹전", "실내", "혼자"],
      hours: "11:00 - 19:00",
      savedBy: 398,
      lat: 37.5207,
      lng: 127.0241,
    },
    {
      id: "gn-serosugil-walk",
      name: "세로수길",
      category: "산책",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 세로수길 일대",
      description: "가로수길과 이어지는 아기자기한 소규모 매장 산책.",
      distance: "0.4km",
      duration: "25분",
      price: "무료",
      tags: ["소규모매장", "아기자기", "실외", "한적함"],
      hours: "상시 이용",
      savedBy: 892,
      lat: 37.5194,
      lng: 127.0201,
    },
    {
      id: "gn-apgujeong-teahouse",
      name: "오설록 티하우스 역삼",
      category: "카페",
      areaId: "gangnam",
      area: "역삼",
      address: "서울 강남구 테헤란로",
      description: "오피스 밀집가에서 잠시 쉬어가는 조용한 티하우스.",
      distance: "1.6km",
      duration: "50분",
      price: "1.5만원대",
      tags: ["티하우스", "고급", "실내", "혼자"],
      hours: "10:00 - 21:00",
      savedBy: 578,
      lat: 37.5006,
      lng: 127.0365,
    },
    {
      id: "gn-apgujeong-popupstore",
      name: "무신사 갤러리 역삼",
      category: "팝업",
      areaId: "gangnam",
      area: "역삼",
      address: "서울 강남구 테헤란로8길",
      description: "매달 브랜드가 바뀌는 갤러리형 팝업스토어.",
      distance: "1.5km",
      duration: "35분",
      price: "무료 입장",
      tags: ["갤러리형", "월간교체", "실내", "친구모임"],
      hours: "11:00 - 20:00",
      savedBy: 1121,
      lat: 37.5018,
      lng: 127.0378,
    },
    {
      id: "gn-apgujeong-sculpture",
      name: "센터필드 조각공원",
      category: "전시",
      areaId: "gangnam",
      area: "역삼",
      address: "서울 강남구 테헤란로 센터필드",
      description: "오피스 빌딩 앞 야외 정원에 놓인 조각 작품 전시.",
      distance: "1.3km",
      duration: "40분",
      price: "1.2만원",
      tags: ["조각", "야외정원", "실외", "한적함"],
      hours: "10:00 - 18:00",
      savedBy: 503,
      lat: 37.5001,
      lng: 127.0361,
    },
    {
      id: "gn-apgujeong-hanriver-walk",
      name: "역삼 테헤란로 가로수길",
      category: "산책",
      areaId: "gangnam",
      area: "역삼",
      address: "서울 강남구 테헤란로 일대",
      description: "빌딩숲 사이 가로수 그늘을 따라 걷는 오피스가 산책.",
      distance: "1.8km",
      duration: "40분",
      price: "무료",
      tags: ["가로수", "오피스가", "실외", "한적함"],
      hours: "24시간",
      savedBy: 1467,
      lat: 37.5003,
      lng: 127.0355,
    },
    {
      id: "gn-cheongdam-brunch-lounge",
      name: "라운지엑스 논현",
      category: "카페",
      areaId: "gangnam",
      area: "논현",
      address: "서울 강남구 논현동 학동로",
      description: "라운지형 좌석에서 즐기는 프라이빗 브런치.",
      distance: "2.0km",
      duration: "60분",
      price: "2.8만원대",
      tags: ["라운지", "프라이빗", "실내", "고급스러운"],
      hours: "10:00 - 21:00",
      savedBy: 1289,
      lat: 37.5135,
      lng: 127.0258,
    },
    {
      id: "gn-cheongdam-flower-popup",
      name: "부에나비스타 플라워 논현",
      category: "팝업",
      areaId: "gangnam",
      area: "논현",
      address: "서울 강남구 학동로",
      description: "럭셔리 플라워 브랜드의 원데이 클래스 팝업.",
      distance: "2.1km",
      duration: "45분",
      price: "5만원대",
      tags: ["플라워", "클래스", "실내", "고급스러운"],
      hours: "11:00 - 19:00",
      savedBy: 712,
      lat: 37.5124,
      lng: 127.0264,
    },
    {
      id: "gn-cheongdam-photo-gallery",
      name: "매거진 아카이브 논현",
      category: "전시",
      areaId: "gangnam",
      area: "논현",
      address: "서울 강남구 논현로20길",
      description: "패션 화보와 매거진 아카이브를 함께 보는 전시.",
      distance: "1.9km",
      duration: "35분",
      price: "1만원",
      tags: ["매거진", "아카이브", "실내", "혼자"],
      hours: "11:00 - 19:00",
      savedBy: 456,
      lat: 37.5116,
      lng: 127.0239,
    },
    {
      id: "gn-cheongdam-luxury-walk",
      name: "강남역 뒷골목 산책",
      category: "산책",
      areaId: "gangnam",
      area: "강남역",
      address: "서울 강남구 강남대로102길 일대",
      description: "오피스와 술집이 섞인 강남역 뒷골목 로컬 산책.",
      distance: "2.3km",
      duration: "35분",
      price: "무료",
      tags: ["뒷골목", "로컬", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 1893,
      lat: 37.4989,
      lng: 127.0293,
    },
    {
      id: "gn-sinsa-deli-cafe",
      name: "폴바셋 델리 신논현",
      category: "카페",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로 언주로",
      description: "가볍게 먹기 좋은 델리 메뉴가 강점인 카페.",
      distance: "0.9km",
      duration: "40분",
      price: "1.3만원대",
      tags: ["델리", "가벼운식사", "실내", "혼자"],
      hours: "10:00 - 21:00",
      savedBy: 687,
      lat: 37.5035,
      lng: 127.0244,
    },
    {
      id: "gn-sinsa-arttoy-popup",
      name: "카멜커피 아트토이 팝업 신논현",
      category: "팝업",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 봉은사로9길",
      description: "리미티드 에디션 아트토이를 선보이는 팝업.",
      distance: "0.8km",
      duration: "30분",
      price: "무료 입장",
      tags: ["아트토이", "리미티드", "실내", "친구모임"],
      hours: "12:00 - 20:00",
      savedBy: 954,
      lat: 37.5059,
      lng: 127.0261,
    },
    {
      id: "gn-sinsa-light-gallery",
      name: "라이트하우스 신논현",
      category: "전시",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로12길",
      description: "빛과 공간을 활용한 몰입형 조명 예술 전시.",
      distance: "1.0km",
      duration: "40분",
      price: "1.3만원",
      tags: ["조명예술", "몰입형", "실내", "데이트"],
      hours: "13:00 - 21:00",
      savedBy: 811,
      lat: 37.5024,
      lng: 127.0247,
    },
    {
      id: "gn-garosugil-brunch-garden",
      name: "가로수길 가든테라스",
      category: "카페",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 가로수길12길",
      description: "테라스 정원 좌석이 있는 여유로운 브런치 공간.",
      distance: "0.6km",
      duration: "55분",
      price: "1.9만원대",
      tags: ["테라스", "정원", "실외", "데이트"],
      hours: "09:00 - 21:00",
      savedBy: 1056,
      lat: 37.5191,
      lng: 127.0227,
    },
    {
      id: "gn-garosugil-sneaker-popup",
      name: "나이키 라이즈 가로수길",
      category: "팝업",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 가로수길14길",
      description: "글로벌 스니커즈 브랜드의 한정판 공개 팝업.",
      distance: "0.5km",
      duration: "35분",
      price: "무료 입장",
      tags: ["스니커즈", "한정판", "실내", "친구모임"],
      hours: "11:00 - 21:00",
      savedBy: 1743,
      lat: 37.5199,
      lng: 127.0209,
    },
    {
      id: "gn-garosugil-back-alley-walk",
      name: "가로수길 뒷골목",
      category: "산책",
      areaId: "gangnam",
      area: "가로수길",
      address: "서울 강남구 가로수길 뒷골목 일대",
      description: "관광객이 적은 조용한 가로수길 뒷골목 산책.",
      distance: "0.4km",
      duration: "25분",
      price: "무료",
      tags: ["뒷골목", "한적함", "실외", "한적함"],
      hours: "상시 이용",
      savedBy: 623,
      lat: 37.5188,
      lng: 127.0212,
    },
    {
      id: "gn-apgujeong-winebar",
      name: "비노샵 역삼",
      category: "카페",
      areaId: "gangnam",
      area: "역삼",
      address: "서울 강남구 역삼로",
      description: "저녁 코스 마무리로 좋은 프라이빗 와인바.",
      distance: "1.7km",
      duration: "80분",
      price: "4.5만원대",
      tags: ["와인", "프라이빗", "실내", "데이트"],
      hours: "18:00 - 01:00",
      savedBy: 892,
      lat: 37.5012,
      lng: 127.0348,
    },
    {
      id: "gn-apgujeong-living-popup",
      name: "일룸 리빙 팝업 역삼",
      category: "팝업",
      areaId: "gangnam",
      area: "역삼",
      address: "서울 강남구 역삼로7길",
      description: "북유럽 감성 리빙 브랜드의 쇼룸형 팝업.",
      distance: "1.4km",
      duration: "40분",
      price: "무료 입장",
      tags: ["리빙", "쇼룸", "실내", "친구모임"],
      hours: "11:00 - 20:00",
      savedBy: 776,
      lat: 37.4995,
      lng: 127.0338,
    },
    {
      id: "gn-apgujeong-street-gallery",
      name: "커먼그라운드 역삼",
      category: "전시",
      areaId: "gangnam",
      area: "역삼",
      address: "서울 강남구 역삼로 일대",
      description: "스트리트 컬처와 브랜드 협업을 다루는 갤러리.",
      distance: "1.6km",
      duration: "35분",
      price: "무료",
      tags: ["스트리트컬처", "협업", "실내", "친구모임"],
      hours: "12:00 - 20:00",
      savedBy: 634,
      lat: 37.5024,
      lng: 127.0342,
    },
    {
      id: "gn-cheongdam-coffeebar",
      name: "센터커피 강남역",
      category: "카페",
      areaId: "gangnam",
      area: "강남역",
      address: "서울 강남구 강남대로100길",
      description: "바 형식으로 즐기는 스페셜티 원두 커피바.",
      distance: "2.4km",
      duration: "35분",
      price: "1만원대",
      tags: ["스페셜티", "바형식", "실내", "혼자"],
      hours: "09:00 - 20:00",
      savedBy: 665,
      lat: 37.4991,
      lng: 127.0269,
    },
    {
      id: "gn-cheongdam-jewelry-gallery",
      name: "강남 주얼리쇼케이스",
      category: "전시",
      areaId: "gangnam",
      area: "강남역",
      address: "서울 강남구 강남대로 지하상가",
      description: "하이엔드 주얼리 브랜드의 프라이빗 쇼케이스.",
      distance: "2.2km",
      duration: "40분",
      price: "무료(초대제)",
      tags: ["주얼리", "쇼케이스", "실내", "고급스러운"],
      hours: "11:00 - 19:00",
      savedBy: 542,
      lat: 37.4983,
      lng: 127.0273,
    },
    {
      id: "gn-cheongdam-neighborhood-walk",
      name: "강남역 8번출구 거리",
      category: "산책",
      areaId: "gangnam",
      area: "강남역",
      address: "서울 강남구 강남대로 8번출구 일대",
      description: "약속 장소로 유명한 강남역 8번출구 앞 거리 산책.",
      distance: "2.5km",
      duration: "40분",
      price: "무료",
      tags: ["약속장소", "번화가", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 987,
      lat: 37.4975,
      lng: 127.0280,
    },
    {
      id: "gn-dosan-cafestreet-walk",
      name: "신논현 카페스트리트",
      category: "산책",
      areaId: "gangnam",
      area: "신논현",
      address: "서울 강남구 신논현로 일대",
      description: "감각적인 카페와 쇼룸이 이어지는 신논현 산책.",
      distance: "1.1km",
      duration: "35분",
      price: "무료",
      tags: ["카페거리", "쇼룸", "실외", "활기참"],
      hours: "상시 이용",
      savedBy: 1421,
      lat: 37.5052,
      lng: 127.0257,
    },
  ],
};

export const categoryTone: Record<PlaceCategory, string> = {
  전시: "#7c6cf2",
  카페: "#a36a3d",
  팝업: "#e87957",
  산책: "#2f9f8f",
};

export function getPlaceImageUrl(id: string, width = 240, height = 320): string {
  return `https://picsum.photos/seed/${id}/${width}/${height}`;
}

export function getPlaceById(id: string): MobilePlace | undefined {
  return Object.values(placesByArea)
    .flat()
    .find((place) => place.id === id);
}

export function getPlacesByIds(ids: string[]): MobilePlace[] {
  return ids
    .map((id) => getPlaceById(id))
    .filter((place): place is MobilePlace => Boolean(place));
}

export function getTotalMinutes(places: MobilePlace[]): number {
  return places.reduce((total, place) => {
    const minutes = Number.parseInt(place.duration, 10);
    return Number.isNaN(minutes) ? total : total + minutes;
  }, 0);
}

const TRIP_AUTHORS: { handle: string; name: string }[] = [
  { handle: "mina.route", name: "Mina" },
  { handle: "walk.seoul", name: "Walk Seoul" },
  { handle: "popup.finder", name: "Popup Finder" },
  { handle: "cafe.hopper", name: "카페홀릭" },
  { handle: "seoul.dailytrip", name: "서울일상여행" },
  { handle: "brunch.lover", name: "브런치러버" },
  { handle: "night.walker", name: "밤산책러" },
  { handle: "trend.setter", name: "트렌드세터" },
  { handle: "local.guide", name: "동네가이드" },
  { handle: "photo.spot", name: "포토스팟헌터" },
  { handle: "date.planner", name: "데이트플래너" },
  { handle: "weekend.list", name: "주말리스트" },
];

type TripTheme = {
  title: (areaName: string) => string;
  description: string;
  categories: PlaceCategory[];
};

const TRIP_THEMES: TripTheme[] = [
  {
    title: (area) => `${area} 전시와 팝업을 잇는 오후`,
    description: "핫한 팝업과 전시를 골고루 즐기는 나들이 코스.",
    categories: ["전시", "팝업", "카페", "팝업"],
  },
  {
    title: (area) => `${area}에서 걷고 마시는 하루`,
    description: "숲길 산책과 로스터리 카페로 여유롭게 즐기는 코스.",
    categories: ["산책", "카페", "산책", "카페"],
  },
  {
    title: (area) => `${area} 팝업 나들이`,
    description: "요즘 화제인 팝업스토어를 골라 도는 코스.",
    categories: ["팝업", "카페", "팝업", "전시"],
  },
  {
    title: (area) => `${area} 조용한 카페 투어`,
    description: "혼자 가기 좋은 감성 카페들을 이어 걷는 코스.",
    categories: ["카페", "카페", "산책", "카페"],
  },
  {
    title: (area) => `${area} 핫플 도장깨기 코스`,
    description: "지금 가장 붐비는 곳들만 골라 빠르게 도는 코스.",
    categories: ["팝업", "전시", "팝업", "카페"],
  },
  {
    title: (area) => `${area} 감성 산책로`,
    description: "전시와 산책을 번갈아, 사진 찍기 좋은 코스.",
    categories: ["산책", "전시", "산책", "카페"],
  },
  {
    title: (area) => `${area} 주말 브런치 나들이`,
    description: "여유로운 브런치로 시작해 팝업까지 즐기는 코스.",
    categories: ["카페", "산책", "팝업", "카페"],
  },
  {
    title: (area) => `${area} 전시 마니아를 위한 코스`,
    description: "전시를 연달아 즐기고 싶은 사람을 위한 코스.",
    categories: ["전시", "전시", "카페", "산책"],
  },
  {
    title: (area) => `${area} 저녁 데이트 코스`,
    description: "팝업 구경 후 분위기 좋은 카페로 마무리하는 코스.",
    categories: ["카페", "팝업", "산책", "카페"],
  },
  {
    title: (area) => `${area} 로컬 숨은 명소 코스`,
    description: "덜 알려졌지만 가볼 만한 곳들을 모은 코스.",
    categories: ["산책", "카페", "전시", "팝업"],
  },
];

function dateDaysBefore(anchor: string, days: number): string {
  const date = new Date(`${anchor}T00:00:00Z`);
  date.setUTCDate(date.getUTCDate() - days);
  return date.toISOString().slice(0, 10);
}

function generateAreaTrips(areaId: AreaId, areaIndex: number): FeedTrip[] {
  const areaName = areaMeta[areaId].name;
  const places = placesByArea[areaId];

  return TRIP_THEMES.map((theme, themeIndex) => {
    const used = new Set<string>();
    const picked: MobilePlace[] = [];

    theme.categories.forEach((category, categoryIndex) => {
      const candidates = places.filter((place) => place.category === category && !used.has(place.id));
      if (candidates.length === 0) {
        return;
      }
      const offset = (themeIndex * 7 + categoryIndex * 3 + areaIndex * 5) % candidates.length;
      const place = candidates[offset];
      used.add(place.id);
      picked.push(place);
    });

    const seed = (areaIndex * 31 + themeIndex * 17 + 11) % 97;
    const author = TRIP_AUTHORS[(areaIndex * 4 + themeIndex) % TRIP_AUTHORS.length];

    return {
      id: `seed-${areaId}-${themeIndex}`,
      title: theme.title(areaName),
      description: theme.description,
      authorHandle: author.handle,
      authorName: author.name,
      areaId,
      visibility: "public",
      placeIds: picked.map((place) => place.id),
      likes: 120 + seed * 9,
      comments: 4 + (seed % 23),
      saved: 40 + ((seed * 3) % 180),
      rankScore: 55 + (seed % 40),
      isMine: false,
      publishedAt: dateDaysBefore("2026-08-05", areaIndex * 3 + themeIndex),
    } satisfies FeedTrip;
  });
}

export const seedFeedTrips: FeedTrip[] = (Object.keys(areaMeta) as AreaId[]).flatMap(
  (areaId, areaIndex) => generateAreaTrips(areaId, areaIndex),
);

function haversineKm(a: { lat: number; lng: number }, b: { lat: number; lng: number }): number {
  const R = 6371;
  const dLat = ((b.lat - a.lat) * Math.PI) / 180;
  const dLng = ((b.lng - a.lng) * Math.PI) / 180;
  const lat1 = (a.lat * Math.PI) / 180;
  const lat2 = (b.lat * Math.PI) / 180;
  const h =
    Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;

  return 2 * R * Math.asin(Math.sqrt(h));
}

export function nearestAreaId(point: { lat: number; lng: number }): AreaId {
  const areaIds = Object.keys(areaMeta) as AreaId[];
  return areaIds.reduce((closest, candidate) =>
    haversineKm(point, areaMeta[candidate].center) < haversineKm(point, areaMeta[closest].center)
      ? candidate
      : closest,
  );
}

export type MenuItem = {
  name: string;
  price: string;
  baseLikes: number;
};

const CAFE_MENU_POOL: { name: string; price: string }[] = [
  { name: "아메리카노", price: "4,500원" },
  { name: "카페라떼", price: "5,000원" },
  { name: "바닐라라떼", price: "5,500원" },
  { name: "콜드브루", price: "5,500원" },
  { name: "카푸치노", price: "5,000원" },
  { name: "크루아상", price: "4,800원" },
  { name: "스콘", price: "4,500원" },
  { name: "치즈케이크", price: "7,500원" },
  { name: "티라미수", price: "7,000원" },
  { name: "레몬에이드", price: "6,000원" },
  { name: "얼그레이 티", price: "5,500원" },
  { name: "핸드드립 커피", price: "6,500원" },
  { name: "허니브레드", price: "9,500원" },
  { name: "마카롱 세트", price: "8,000원" },
  { name: "바스크 치즈케이크", price: "7,800원" },
];

function hashString(value: string): number {
  let hash = 0;
  for (let i = 0; i < value.length; i++) {
    hash = (hash * 31 + value.charCodeAt(i)) >>> 0;
  }
  return hash;
}

export function getCafeMenu(place: MobilePlace): MenuItem[] {
  const seed = hashString(place.id);
  const count = 4 + (seed % 3);
  const startIndex = seed % CAFE_MENU_POOL.length;

  return Array.from({ length: count }, (_, i) => {
    const index = (startIndex + i * 7) % CAFE_MENU_POOL.length;
    const base = CAFE_MENU_POOL[index];
    const likeSeed = hashString(`${place.id}:${base.name}`);

    return { ...base, baseLikes: 8 + (likeSeed % 65) };
  });
}
